workflows:
  ios-test-build:
    name: iOS Test Build (Unsigned)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install pods
        script: |
          find . -name "Podfile" -exec dir dirname {} \; | xargs -n1 -I % sh -c 'cd "%"; pod install'
      - name: Flutter build ipa (Unsigned)
        script: |
          # Hesap onayi gelene kadar imzasiz build aliyoruz
          flutter build ios --release --no-codesign
    artifacts:
      - "build/ios/ipa/*.ipa"
      - "/tmp/xcodebuild_logs/*.log"
      - "*.dSYM.zip"
    publishing:
      email:
        recipients:
          - benimmarketimmm@gmail.com
